import type { NextPage } from "next";
import Head from "next/head";
import AuthShowcase from "./components/AuthShowcase";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Workout Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-5xl font-extrabold leading-normal text-white md:text-[5rem]">
          <span className="text-purple-300">Workout</span> 🏋️ Tracker
        </h1>
        <AuthShowcase />
      </main>
    </div>
  );
};

export default Home;
