import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import AuthShowcase from "./components/AuthShowcase";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.example.hello.useQuery({
    text: "from tRPC",
  });

  return (
    <>
      <Head>
        <title>Workout Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          <span className="text-purple-300">Workout</span> 🏋️ Tracker
        </h1>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {isLoading ? <p>Loading..</p> : <p>{data?.greeting}</p>}
        </div>
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;
